name: pos_dev_web_disp_moveis_flutter_widgets_states1
description: 'Aplicativo Flutter demonstrando o uso de widgets Stateful e Stateless com tema dinâmico.'

# Evita que o projeto seja publicado no pub.dev (ótimo para projetos locais)
publish_to: 'none'

# Versão do app (ex: 1.0.0+1)
version: 1.0.0+1

# Define a versão mínima do SDK Dart necessária
environment:
  sdk: ^3.7.2

# Dependências principais que o app precisa para funcionar
dependencies:
  flutter:
    sdk: flutter

  # Ícones estilo iOS (opcional)
  cupertino_icons: ^1.0.8

  # Provider: gerenciador de estado usado para alternar o tema
  provider: ^6.1.0

# Dependências usadas apenas durante o desenvolvimento ou testes
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Regras de boas práticas e lint do Flutter
  flutter_lints: ^5.0.0

# Configurações específicas do Flutter
flutter:
  # Inclui os ícones padrão do Material Design
  uses-material-design: true

  # Exemplos de como adicionar imagens, fontes, etc.
  # Para usar, descomente e adicione seus próprios arquivos
  # assets:
  #   - images/minha_imagem.png

  # fonts:
  #   - family: MinhaFonte
  #     fonts:
  #       - asset: fonts/MinhaFonte-Regular.ttf
